import "@/styles/globals.css";
import Provider from "@/components/auth/provider";


export const metadata = {
    title: 'elluis.codes',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className="font-objektiv-variable">
        <Provider>
            {children}
        </Provider>

        </body>
        </html>
    )
}
